import { CloudShadowsLayer } from "../effects/CloudShadows.js";
import { StructuralShadowsLayer } from "../effects/StructuralShadows.js";
import { CanopyLayer } from "../effects/Canopy.js";
import { MetallicShineLayer } from "../effects/MetallicShine.js";
import { WaterFXLayer } from "../effects/Water.js";
import { PrismLayer } from "../effects/Prism.js";
import { IridescenceLayer } from "../effects/Iridescence.js";
import { HeatDistortionLayer } from "../effects/HeatDistortion.js";

/***************************************************************************************
 *
 *                              RESOURCE MANAGER
 *
 *  PURPOSE:
 *  The ResourceManager acts as a centralized hub for all shared rendering resources
 *  (e.g., PIXI.RenderTextures) used by the various effects in Map Shine. Its mission
 *  is to untangle the "web of dependencies" where individual layers and filters directly
 *  pull data from each other, leading to timing issues, redundant work, and difficult
 *  debugging.
 *
 *  ARCHITECTURE (THE FACADE & CACHING PATTERN):
 *  1. Centralized Access: Instead of an effect layer knowing about `IlluminationManager`,
 *     `CloudShadowsLayer`, etc., it will only ask the ResourceManager for what it needs
 *     (e.g., `resourceManager.getIlluminationTexture()`).
 *
 *  2. Lazy Generation & Caching: The manager creates resources only when they are first
 *     requested within a single animation frame. It then caches that resource and serves
 *     the cached version to any other effect that asks for it in the same frame. The
 *     cache is cleared at the start of the next frame. This guarantees that resources
 *     are always up-to-date for the current frame and are only ever generated once.
 *
 *  3. Dependency Management: The manager will eventually understand the entire render
 *     pipeline. If a resource depends on another (e.g., a corrected illumination texture
 *     needs the base illumination and a shadow mask), the manager will ensure the
 *     dependencies are generated first before creating the final product.
 *
 *  MIGRATION PLAN:
 *  The migration to this new system is being done incrementally and with caution. Each
 *  effect is being refactored one by one to source its dependencies from this manager
 *  instead of its original source. This ensures stability throughout the transition.
 *
 ***************************************************************************************/
export class ResourceManager {
  constructor() {
    this._frameCache = {};
    this._destroyed = false;
  }

  /**

          Initializes the manager by acquiring references to other essential managers.

          This should be called once during canvas setup.
          */
  initialize() {
    console.log("Map Shine | ResourceManager initialized.");
  }

  /**

          Cleans up resources. Called during canvas tear down.
          */
  destroy() {
    this._frameCache = {};
    this._destroyed = true;
    console.log("Map Shine | ResourceManager destroyed.");
  }

  /**

          Called at the start of each animation frame to clear cached resources.
          */
  onFrameStart() {
    this._frameCache = {};
  }

  /**

          Retrieves the mask texture generated by the CloudShadowsLayer.

          Caches the texture for the duration of the current frame.

          @returns {PIXI.RenderTexture|null} The outdoors mask texture.
          */
  getOutdoorsMask() {
    if (this._destroyed) return null;
    
    // CRITICAL: Skip rendering during scene transitions to prevent accessing destroyed objects
    if (game.mapShine?.transitionActive) return null;

    if (this._frameCache.outdoorsMask) {
      return this._frameCache.outdoorsMask;
    }

    const cloudLayer = canvas.layers.find(
      (l) => l instanceof CloudShadowsLayer
    );
    if (!cloudLayer) return null;

    // Ensure the mask is rendered for the current frame if an update is pending.
    if (cloudLayer._needsMaskUpdate) {
      cloudLayer.renderMask();
    }

    const texture = cloudLayer.getMaskTexture();
    this._frameCache.outdoorsMask = texture;
    return texture;
  }

  /**

          Retrieves the final rendered cloud shadow texture from the CloudShadowsLayer.

          If the texture hasn't been rendered this frame, this will command the layer to render it.

          Caches the texture for the duration of the current frame.

          @returns {PIXI.RenderTexture|null} The cloud shadow texture.
          */
  getCloudShadowTexture(deltaTime) {
    if (this._destroyed) return null;

    if (this._frameCache.cloudShadowTexture) {
      return this._frameCache.cloudShadowTexture;
    }

    const cloudLayer = canvas.layers.find(
      (l) => l instanceof CloudShadowsLayer
    );
    if (!cloudLayer) return null;

    // Command the layer to render its effect now, passing the deltaTime from the
    // calling animation loop to ensure correct timing.
    cloudLayer.renderEffectNow(deltaTime);

    // Now that it has been rendered, get the resulting texture.
    const texture = cloudLayer.getRawCloudTexture();

    this._frameCache.cloudShadowTexture = texture;
    return texture;
  }

  /**

          Retrieves the raw, unmasked cloud pattern texture from the CloudShadowsLayer.

          This is useful for effects that need the cloud pattern indoors.

          If the texture hasn't been rendered this frame, this will command the layer to render it.

          Caches the texture for the duration of the current frame.

          @param {number} deltaTime - The time since the last frame.

          @returns {PIXI.RenderTexture|null} The raw cloud pattern texture.
          */
  getRawCloudTexture(deltaTime) {
    if (this._destroyed) return null;

    // If another request this frame already generated the raw cloud texture, return it.
    if (this._frameCache.rawCloudTexture) {
      return this._frameCache.rawCloudTexture;
    }

    const cloudLayer = canvas.layers.find(
      (l) => l instanceof CloudShadowsLayer
    );
    if (!cloudLayer) return null;

    // The getCloudShadowTexture method ensures renderEffectNow is called.
    // We can call it to trigger the render, then grab the raw texture we need.
    // This avoids rendering the cloud layer multiple times per frame.
    this.getCloudShadowTexture(deltaTime);

    // Now that the render is guaranteed to have happened, we can get the raw texture.
    const texture = cloudLayer.getRawCloudTexture();
    this._frameCache.rawCloudTexture = texture;
    return texture;
  }

  getLightMask() {
    if (this._destroyed) return null;
    if (this._frameCache.lightMask) {
      return this._frameCache.lightMask;
    }
    if (!game.mapShine.lightMaskManager) return null;

    const texture = game.mapShine.lightMaskManager.getTexture();
    this._frameCache.lightMask = texture;
    return texture;
  }

  getIlluminationTexture() {
    if (this._destroyed) return null;
    return null;
  }

  /**

          Retrieves the raw, unmasked structural pattern texture from the StructuralShadowsLayer.

          This is the combined mask of all _Structural.webp textures.

          Caches the texture for the duration of the current frame.

          @returns {PIXI.RenderTexture|null} The raw structural mask texture.
          */
  getStructuralMask() {
    if (this._destroyed) return null;
    if (this._frameCache.structuralMask) {
      return this._frameCache.structuralMask;
    }

    const layer = canvas.layers.find(
      (l) => l instanceof StructuralShadowsLayer
    );
    if (!layer) return null;

    // This is the key change: we actively command the layer to update its mask
    // if it has flagged that an update is needed (e.g., due to a pan).
    if (layer._needsMaskUpdate) {
      layer.renderMask();
    }

    // This now gets the guaranteed up-to-date combinedMaskTexture
    const texture = layer.getMaskTexture();
    this._frameCache.structuralMask = texture;
    return texture;
  }

  /**

          Retrieves the final rendered canopy shadow texture.

          If not rendered this frame, commands the CanopyLayer to render.

          @param {number} deltaTime - The time since the last frame.

          @returns {PIXI.RenderTexture|null} The canopy shadow texture.
          */
  getCanopyShadowTexture(deltaTime) {
    if (this._destroyed) return null;
    if (this._frameCache.canopyShadowTexture) {
      return this._frameCache.canopyShadowTexture;
    }

    const layer = canvas.layers.find((l) => l instanceof CanopyLayer);
    if (!layer) return null;

    layer.renderEffectNow(deltaTime);
    const texture = layer.finalShadowTexture;
    this._frameCache.canopyShadowTexture = texture;
    return texture;
  }

  /**

          Retrieves the mask texture generated by the CanopyLayer.

          This is the raw _Canopy.webp mask.

          Caches the texture for the duration of the current frame.

          @returns {PIXI.RenderTexture|null} The canopy mask texture.
          */
  getCanopyMask() {
    if (this._destroyed) return null;
    if (this._frameCache.canopyMask) {
      return this._frameCache.canopyMask;
    }

    const layer = canvas.layers.find((l) => l instanceof CanopyLayer);
    if (!layer) return null;

    // This gets the combinedMaskTexture from the MaskedEffectLayer base class
    const texture = layer.getMaskTexture();
    this._frameCache.canopyMask = texture;
    return texture;
  }

  /**

          Retrieves the mask of all visible tokens on the canvas.

          Caches the texture for the duration of the current frame.

          @returns {PIXI.RenderTexture|null} The token mask texture.
          */
  getTokenMask() {
    if (this._destroyed) return null;
    if (this._frameCache.tokenMask) {
      return this._frameCache.tokenMask;
    }

    if (!game.mapShine?.tokenMaskManager) return null;

    const texture = game.mapShine.tokenMaskManager.getMaskTexture();
    this._frameCache.tokenMask = texture;
    return texture;
  }

  /**

          Retrieves a texture representing the combined specular masks for the metallic shine effect.

          This is a pre-computation that does not include the animated shine itself.

          Caches the texture for the duration of the current frame.

          @returns {PIXI.RenderTexture|null} The specular mask texture.
          */
  getMetallicSpecularMask() {
    if (this._destroyed) return null;
    if (this._frameCache.metallicSpecularMask) {
      return this._frameCache.metallicSpecularMask;
    }

    const layer = canvas.layers.find((l) => l instanceof MetallicShineLayer);
    if (!layer) return null;

    // Command the layer to render its specular mask. This is safe as it has no dependencies.
    layer.renderSpecularMask();

    const texture = layer.getSpecularMaskTexture();
    this._frameCache.metallicSpecularMask = texture;
    return texture;
  }

  /**

          Retrieves the final rendered animated metallic shine texture.

          If not generated this frame, commands the MetallicShineLayer to render it.

          @param {number} deltaTime - The time since the last frame.

          @returns {PIXI.RenderTexture|null} The animated shine texture.
          */
  getAnimatedShineTexture(deltaTime) {
    if (this._destroyed) return null;
    if (this._frameCache.animatedShineTexture) {
      return this._frameCache.animatedShineTexture;
    }

    const layer = canvas.layers.find((l) => l instanceof MetallicShineLayer);
    if (!layer) return null;

    if (typeof layer.renderEffectNow === "function") {
      layer.renderEffectNow(deltaTime);
    } else {
      console.warn(
        "ResourceManager: MetallicShineLayer is missing renderEffectNow()"
      );
      return null;
    }

    const texture = layer.getEffectTexture();
    this._frameCache.animatedShineTexture = texture;
    return texture;
  }

  /**

          Retrieves the primary water mask (_Water textures).

          @returns {PIXI.RenderTexture|null}
          */
  getWaterMask() {
    if (this._destroyed) return null;
    if (this._frameCache.waterMask) return this._frameCache.waterMask;

    const layer = canvas.layers.find((l) => l instanceof WaterFXLayer);
    if (!layer) return null;

    // Ensure the mask is rendered for the current frame if an update is pending.
    if (layer._needsMaskUpdate) {
      layer.renderMask();
    }

    const texture = layer.getMaskTexture();
    this._frameCache.waterMask = texture;
    return texture;
  }

  /**

          Retrieves the blurred version of the primary water mask for shoreline detection.

          @returns {PIXI.RenderTexture|null}
          */
  getBlurredWaterMask() {
    if (this._destroyed) return null;
    if (this._frameCache.blurredWaterMask)
      return this._frameCache.blurredWaterMask;

    const layer = canvas.layers.find((l) => l instanceof WaterFXLayer);
    if (!layer?.blurSourceSprite || !layer?.blurredWaterMaskTexture)
      return null;

    // Command the layer to perform the blur operation.
    const waterMask = this.getWaterMask();
    if (layer.blurSourceSprite && waterMask?.baseTexture?.valid && layer.blurredWaterMaskTexture?.valid) {
      layer.blurSourceSprite.texture = waterMask;
      canvas.app.renderer.render(layer.blurSourceSprite, {
        renderTexture: layer.blurredWaterMaskTexture,
        clear: true,
      });
    }

    this._frameCache.blurredWaterMask = layer.blurredWaterMaskTexture;
    return layer.blurredWaterMaskTexture;
  }

  /**

          Retrieves the composite mask of all _Shoreline textures.

          @returns {PIXI.RenderTexture|null}
          */
  getShorelineMask() {
    if (this._destroyed) return null;
    if (this._frameCache.shorelineMask) return this._frameCache.shorelineMask;

    const layer = canvas.layers.find((l) => l instanceof WaterFXLayer);
    if (!layer?.shorelineMaskContainer || !layer?.shorelineMaskTexture)
      return null;

    // Command the layer to render its shoreline mask.
    if (layer.shorelineMaskContainer && !layer.shorelineMaskContainer.destroyed && layer.shorelineMaskTexture?.valid) {
      canvas.app.renderer.render(layer.shorelineMaskContainer, {
        renderTexture: layer.shorelineMaskTexture,
        transform: canvas.stage.transform.worldTransform,
        clear: true,
      });
    }

    this._frameCache.shorelineMask = layer.shorelineMaskTexture;
    return layer.shorelineMaskTexture;
  }

  /**

          Retrieves the wave displacement map for water effects.

          @param {number} deltaTime - Time since the last frame.

          @returns {PIXI.RenderTexture|null}
          */
  getWaterDisplacementMap(deltaTime) {
    if (this._destroyed) return null;
    if (this._frameCache.waterDisplacementMap)
      return this._frameCache.waterDisplacementMap;
    const layer = canvas.layers.find((l) => l instanceof WaterFXLayer);
    if (
      !layer?.displacementFilter ||
      !layer?.displacementSprite ||
      !layer?.displacementTexture
    )
      return null;

    // Command the layer to render its displacement map.
    const timeFactor = game.mapShine.timeControl.timeFactor ?? 1.0;
    layer.displacementFilter.uniforms.u_time += deltaTime * timeFactor;
    if (layer.displacementSprite?.texture?.baseTexture?.valid && !layer.displacementSprite.destroyed && layer.displacementTexture?.valid) {
      // CRITICAL: Check if BatchRenderer is ready before rendering
      const batchRenderer = canvas.app.renderer.plugins?.batch;
      if (!batchRenderer || !batchRenderer._bufferedElements) {
        return null; // Defer rendering until BatchRenderer is initialized
      }
      
      canvas.app.renderer.render(layer.displacementSprite, {
        renderTexture: layer.displacementTexture,
        clear: true,
      });
    }

    this._frameCache.waterDisplacementMap = layer.displacementTexture;
    return layer.displacementTexture;
  }

  /**
   * Retrieves the rendered texture of the biofilm particles.
   * Caches the texture for the duration of the current frame.
   * @returns {PIXI.RenderTexture|null} The biofilm particle texture.
   */
  getBiofilmOutputTexture() {
    if (this._destroyed) return null;
    if (this._frameCache.biofilmOutputTexture) {
      return this._frameCache.biofilmOutputTexture;
    }

    const particleManager = game.mapShine.particleManager;
    if (!particleManager) return null;

    const biofilmController = particleManager.controllers.get("biofilm");
    if (
      !biofilmController ||
      typeof biofilmController.getOutputTexture !== "function"
    ) {
      return null;
    }

    const texture = biofilmController.getOutputTexture();
    this._frameCache.biofilmOutputTexture = texture;
    return texture;
  }

  /**
   * Retrieves the distortion noise texture from the PrismLayer.
   * Caches the texture for the duration of the current frame.
   * @returns {PIXI.RenderTexture|null} The prism distortion noise texture.
   */
  getPrismDistortionNoise() {
    if (this._destroyed) return null;
    if (this._frameCache.prismDistortionNoise) {
      return this._frameCache.prismDistortionNoise;
    }

    const layer = canvas.layers.find((l) => l instanceof PrismLayer);
    if (!layer?.distortionNoiseManager) return null;

    const texture = layer.distortionNoiseManager.getTexture();
    this._frameCache.prismDistortionNoise = texture;
    return texture;
  }

  /**
   * Retrieves the distortion noise texture from the IridescenceLayer.
   * Caches the texture for the duration of the current frame.
   * @returns {PIXI.RenderTexture|null} The iridescence distortion noise texture.
   */
  getIridescenceDistortionNoise() {
    if (this._destroyed) return null;
    if (this._frameCache.iridescenceDistortionNoise) {
      return this._frameCache.iridescenceDistortionNoise;
    }

    const layer = canvas.layers.find((l) => l instanceof IridescenceLayer);
    if (!layer?.distortionNoiseManager) return null;

    const texture = layer.distortionNoiseManager.getTexture();
    this._frameCache.iridescenceDistortionNoise = texture;
    return texture;
  }

  /**
   * Retrieves the heat distortion noise texture from the HeatDistortionLayer.
   * This layer renders noise inline rather than using a NoiseTextureManager.
   * Caches the texture for the duration of the current frame.
   * @returns {PIXI.RenderTexture|null} The heat distortion noise texture.
   */
  getHeatDistortionNoise() {
    if (this._destroyed) return null;
    if (this._frameCache.heatDistortionNoise) {
      return this._frameCache.heatDistortionNoise;
    }

    const layer = canvas.layers.find((l) => l instanceof HeatDistortionLayer);
    if (!layer?.noiseTexture) return null;

    const texture = layer.noiseTexture;
    this._frameCache.heatDistortionNoise = texture;
    return texture;
  }

  /**
   * Retrieves the composite mask of all _NoWater textures.
   * Used to exclude tiles (like trees and bushes) from water distortion effects.
   * Caches the texture for the duration of the current frame.
   * @returns {PIXI.RenderTexture|null} The noWater exclusion mask texture.
   */
  getNoWaterMask() {
    if (this._destroyed) return null;
    if (this._frameCache.noWaterMask) return this._frameCache.noWaterMask;

    const layer = canvas.layers.find((l) => l instanceof WaterFXLayer);
    if (!layer?.noWaterMaskContainer || !layer?.noWaterMaskTexture)
      return null;

    // Command the layer to render its noWater mask if needed
    if (layer._needsNoWaterMaskUpdate && layer.noWaterMaskContainer && !layer.noWaterMaskContainer.destroyed && layer.noWaterMaskTexture?.valid) {
      canvas.app.renderer.render(layer.noWaterMaskContainer, {
        renderTexture: layer.noWaterMaskTexture,
        transform: canvas.stage.transform.worldTransform,
        clear: true,
      });
      layer._needsNoWaterMaskUpdate = false;
    }

    this._frameCache.noWaterMask = layer.noWaterMaskTexture;
    return layer.noWaterMaskTexture;
  }
}