export const Texture = globalThis.PIXI?.Texture;
export const RenderTexture = globalThis.PIXI?.RenderTexture;
export const Filter = globalThis.PIXI?.Filter;
export const MIPMAP_MODES = globalThis.PIXI?.MIPMAP_MODES;
export const SCALE_MODES = globalThis.PIXI?.SCALE_MODES;
export const BLEND_MODES = globalThis.PIXI?.BLEND_MODES;
export const UPDATE_PRIORITY = globalThis.PIXI?.UPDATE_PRIORITY;
export const WRAP_MODES = globalThis.PIXI?.WRAP_MODES;
export const TYPES = globalThis.PIXI?.TYPES;
export const Program = globalThis.PIXI?.Program;
export const Matrix = globalThis.PIXI?.Matrix;
export const State = globalThis.PIXI?.State;
export const DRAW_MODES = globalThis.PIXI?.DRAW_MODES;
export const LINE_CAP = globalThis.PIXI?.LINE_CAP;
export const LINE_JOIN = globalThis.PIXI?.LINE_JOIN;
export const Uint8Array = globalThis.Uint8Array;
export const Float32Array = globalThis.Float32Array;
export const PIXI = globalThis.PIXI; // expose the global PIXI
